//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by CodeSmith Template.
//     Creater: dylan
//     Date:    2017/10/24 14:30
//     Version: 2.0.0.0
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using DMSFrame;
namespace TaskManager.Entity
{
    /// <summary>
    /// 
    /// </summary>
    [Serializable]
    [TableMapping(Name = "P_RPCMonitor", PrimaryKey = "ID", ConfigName = "TaskManager")]
    public class P_RPCMonitor : BaseEntity
    {

        #region Private Properties

        private int? _iD;//
        private string _iP;//Rpc地址
        private int? _port;//端口
        private string _assembly;//程序集
        private string _type;//类型
        private string _method;//执行方法
        private bool? _isSuccess;//是否正常
        private DateTime? _createdOn;//

        #endregion

        #region Public Properties

        /// <summary>
        /// .
        /// </summary>
        [ColumnMapping(Name = "ID")]
        public int? ID
        {
            get { return _iD; }
            set { this.OnBasePropertyChanged<int?>("ID", value, ref _iD); }
        }

        /// <summary>
        /// Rpc地址.
        /// </summary>
        [ColumnMapping(Name = "IP")]
        public string IP
        {
            get { return _iP; }
            set { this.OnBasePropertyChanged("IP", 64, value, ref _iP); }
        }

        /// <summary>
        /// 端口.
        /// </summary>
        [ColumnMapping(Name = "Port")]
        public int? Port
        {
            get { return _port; }
            set { this.OnBasePropertyChanged<int?>("Port", value, ref _port); }
        }

        /// <summary>
        /// 程序集.
        /// </summary>
        [ColumnMapping(Name = "Assembly")]
        public string Assembly
        {
            get { return _assembly; }
            set { this.OnBasePropertyChanged("Assembly", 256, value, ref _assembly); }
        }

        /// <summary>
        /// 类型.
        /// </summary>
        [ColumnMapping(Name = "Type")]
        public string Type
        {
            get { return _type; }
            set { this.OnBasePropertyChanged("Type", 512, value, ref _type); }
        }

        /// <summary>
        /// 执行方法.
        /// </summary>
        [ColumnMapping(Name = "Method")]
        public string Method
        {
            get { return _method; }
            set { this.OnBasePropertyChanged("Method", 512, value, ref _method); }
        }

        /// <summary>
        /// 是否正常.
        /// </summary>
        [ColumnMapping(Name = "IsSuccess")]
        public bool? IsSuccess
        {
            get { return _isSuccess; }
            set { this.OnBasePropertyChanged<bool?>("IsSuccess", value, ref _isSuccess); }
        }

        /// <summary>
        /// .
        /// </summary>
        [ColumnMapping(Name = "CreatedOn")]
        public DateTime? CreatedOn
        {
            get { return _createdOn; }
            set { this.OnBasePropertyChanged<DateTime?>("CreatedOn", value, ref _createdOn); }
        }

        #endregion

    }
}


